function [training, validation, test] = hapt_subject(hapt)
    [training, validation, test] = partition_dataset( ...
        [hapt.train.feature_data; hapt.test.feature_data], ...
        [hapt.train.subject_labels; hapt.test.subject_labels] );
end
