function [training, test] = hapt_activity(hapt)
    training = struct( ...
        'X', hapt.train.feature_data, ...
        'Y', hapt.train.activity_labels ...
    );

    test = struct( ...
        'X', hapt.test.feature_data, ...
        'Y', hapt.test.activity_labels ...
    );
end
