%{
	https://archive.ics.uci.edu/ml/datasets/Smartphone-Based+Recognition+of+Human+Activities+and+Postural+Transitions
%}
function hapt = import_hapt(hapt_dir)
    hapt = struct( ...
        'activities', { importdata( strcat( hapt_dir, 'activity_labels.txt' ) ) }, ...
        'features', { importdata( strcat( hapt_dir, 'features.txt' ) ) }, ...
        'train', struct( ...
            'feature_data', importdata( strcat( hapt_dir, 'Train/X_train.txt' ) ), ...
            'activity_labels', importdata( strcat( hapt_dir, 'Train/y_train.txt' ) ), ...
            'subject_labels', importdata( strcat( hapt_dir, 'Train/subject_id_train.txt' ) ) ...
        ), ...
        'test', struct( ...
            'feature_data', importdata( strcat( hapt_dir, 'Test/X_test.txt' ) ), ...
            'activity_labels', importdata( strcat( hapt_dir, 'Test/y_test.txt' ) ), ...
            'subject_labels', importdata( strcat( hapt_dir, 'Test/subject_id_test.txt' ) ) ...
        ) ...
    );
end
